/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toolrentalservice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApplicationRunnerTest {
    @Test void appHasAGreeting() {
        ApplicationRunner classUnderTest = new ApplicationRunner();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
